GET http://127.0.0.1:1234/users
Content-Type: application/json

{}

###

POST http://127.0.0.1:1234/users
Content-Type: application/json

{}

###

PUT http://127.0.0.1:1234/users/1
Content-Type: application/json

{}

###

PATCH http://127.0.0.1:1234/users/1
Content-Type: application/json

{}

###

DELETE http://127.0.0.1:1234/users/1
Content-Type: application/json

{}

###